# Site settings
title: "KeePassXC Password Manager"
baseurl: ""
url: "https://keepassxc.org"

github: keepassx-reboot

# Build settings
markdown: kramdown
permalink: /:title

# Latest downloads
collections:
  downloads:
    output: true
