title = 'KeePassXC Password Manager'
baseURL = 'https://keepassxc.org'
languageCode = 'en-us'

[module]
  [[module.mounts]]
  source = "assets"
  target = "assets"

  [[module.mounts]]
  source = "node_modules/"
  target = "assets/node_modules"

  [[module.mounts]]
  source = "static"
  target = "static"

  [[module.mounts]]
  source = "node_modules/@fortawesome/fontawesome-free/webfonts"
  target = "static/assets/fonts/fontawesome"
